# Generated by Django 5.0 on 2026-01-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reported",
            field=models.BooleanField(default=False),
        ),
    ]
